name: swin_small_fine
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py37h06a4308_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1k=h27cfd23_0
  - pip=21.1.3=py37h06a4308_0
  - python=3.7.10=h12debd9_4
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py37h06a4308_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.13.0
    - addict==2.4.0
    - aiohttp==3.7.4.post0
    - anykeystore==0.2
    - apex==0.1
    - async-timeout==3.0.1
    - attrs==21.2.0
    - cachetools==4.2.2
    - chardet==4.0.0
    - charset-normalizer==2.0.3
    - click==8.0.1
    - cryptacular==1.6.2
    - cycler==0.10.0
    - cython==0.29.24
    - decorator==4.4.2
    - decord==0.6.0
    - deepspeed==0.5.4
    - defusedxml==0.7.1
    - einops==0.3.0
    - fairscale==0.4.0
    - filelock==3.0.12
    - fsspec==2021.7.0
    - future==0.18.2
    - google-auth==1.33.1
    - google-auth-oauthlib==0.4.4
    - greenlet==1.1.2
    - grpcio==1.39.0
    - huggingface-hub==0.1.1
    - hupper==1.10.3
    - idna==3.2
    - imageio==2.11.1
    - imageio-ffmpeg==0.4.5
    - importlib-metadata==4.6.1
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib==3.4.2
    - mmcv==1.3.9
    - moviepy==1.0.3
    - multidict==5.1.0
    - ninja==1.10.2.2
    - numpy==1.21.1
    - oauthlib==3.1.1
    - opencv-python==4.5.3.56
    - packaging==21.0
    - pastedeploy==2.1.1
    - pbkdf2==1.3
    - pillow==8.4.0
    - plaster==1.0
    - plaster-pastedeploy==0.7
    - proglog==0.1.9
    - protobuf==3.17.3
    - psutil==5.8.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocoevalcap==1.2
    - pycocotools==2.0.2
    - pydeprecate==0.3.1
    - pyparsing==2.4.7
    - pyramid==2.0
    - pyramid-mailer==0.15.1
    - python-dateutil==2.8.2
    - python-graphviz==0.18.2
    - python3-openid==3.2.0
    - pytorch-lightning==1.4.2
    - pytorch-nlp==0.5.0
    - pyyaml==5.3.1
    - regex==2021.7.6
    - repoze-sendmail==4.4.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - sacremoses==0.0.45
    - scipy==1.7.0
    - six==1.16.0
    - sqlalchemy==1.4.26
    - tensorboard==2.4.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==1.8
    - timm==0.4.12
    - tokenizers==0.10.3
    - torch==1.10.0
    - torchaudio==0.8.0
    - torchmetrics==0.4.1
    - torchtext==0.4.0
    - torchvision==0.9.0+cu111
    - torchviz==0.0.2
    - tqdm==4.61.2
    - transaction==3.0.1
    - transformers==4.12.3
    - translationstring==1.4
    - triton==1.1.1
    - typing-extensions==3.10.0.0
    - urllib3==1.26.6
    - velruse==1.1.1
    - venusian==3.0.0
    - webob==1.8.7
    - werkzeug==2.0.1
    - wtforms==2.3.3
    - wtforms-recaptcha==0.3.2
    - xlsxwriter==3.0.1
    - yapf==0.31.0
    - yarl==1.6.3
    - zipp==3.5.0
    - zope-deprecation==4.4.0
    - zope-interface==5.4.0
    - zope-sqlalchemy==1.6

